//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeCard.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignedUser
    {
        public int AssignedUserId { get; set; }
        public Nullable<int> ProjectManagerId { get; set; }
        public string Status { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
